### ISSUE TITLE
Few seemingly random mods dissappearing every time after updating mods through Rimsort

### ISSUE THREAD

**Issue by JinJanODWan** [RimSort/RimSort#1460]
### Release Type

Compiled (Windows x86-64)

### Version

1.0.50 and 1.0.51

### Operating System

Win11

### Describe the bug

<img width="1291" height="690" alt="Image" src="https://github.com/user-attachments/assets/7334a736-66fa-48a0-806d-e24bba1deb74" />

### Additional context

Title happens, without fail, every single time I use Rimsort's "update mods" feature. Around three to five seemingly unrelated mods disappear from list and then I'm met with incorrect "duplicate mod" message (same amount of invalid mods that were just removed) as seen in screenshot.

Only workaround I have found is finding the missing mods in Workshop , unsubscribing, and resubscribing.

### Code of Conduct

I agree to follow this project's Code of Conduct

### Duplicate Issue Check

I've checked for similar issues and didn't find anything

### Wiki/FAQ Check

I've checked the Wiki for a solution and didn't find a solution

**Comment by Skydea777** [comment]
Same Issue, started again after Updating RimSort to the Current 1.0.51 release, I thought the Problem was only on my end, but I have dozens of seemingly "missing" mods.
Also, after Updating it resets the change time to Linux Base Time January 1, 1970.

Example of one of the Mods I already Resubscribed multiple times:

<img width="950" height="268" alt="Image" src="https://github.com/user-attachments/assets/c55587a8-2a2d-4d81-8368-d1f0a32ed58b" />


And the Issue of Non Updating Mods / Mods not getting recognized it was Updated:

<img width="1030" height="1392" alt="Image" src="https://github.com/user-attachments/assets/d6803a51-9a1e-4806-b4fd-eee701005e16" />


It is more then a bit aggravating.

Have it since Release of the new Version, installed it 1 hour after release.
Reinstalled it.
Restarted the Computer
Checked Rimworld Consistency and so on ~
And so on and so on.

**Comment by JinJanODWan** [comment]
To add to above: my "outdated" mods have also incorrectly started showing 1970 as download date same as above. Also, the list has just gotten longer and longer with each restart of Rimsort.

**Comment by Skydea777** [comment]
Yeah... its getting longer. I rechecked the consistency again and.. yeah, the others are also getting longer.
"Shit's fucked."

<img width="949" height="664" alt="Image" src="https://github.com/user-attachments/assets/fb1cb0b6-0fec-4973-8bb4-b66142c62cc3" />

**Comment by LionelColaso** [comment]
@Patryk-Malinowski does this happen to you ?

**Comment by Skydea777** [comment]
Well the Update to 1.0.52 did not like my mod list...

https://0x0.st/KL7S.log

Crashed as soon as I tried to start the Download:

<img width="779" height="1029" alt="Image" src="https://github.com/user-attachments/assets/c6f0305d-9e33-42f5-ae77-605dde8cdbdf" />

Trying to let it download 940 Mods is seemingly not appreciated.

EDIT:
Also about half of all my mods are suddenly missing the Field "PublishedFileID"

**Comment by JinJanODWan** [comment]
FYI No more out of whack dates for "outdated mods" after 1.0.52 update, **but the original issue still persists**:

<img width="983" height="661" alt="Image" src="https://github.com/user-attachments/assets/91e72836-fe14-4ba1-9303-8070540d43b6" />

Rimsort found _Alpha Bees_ to be out of date. I clicked update all button. As soon as Rimsort refreshes, _Retextured! - Recycle This_ is missing. I have to manually unsubscribe and resubscribe in Steam Workshop to get Rimsort to not see it as an _invalid item_ in my list.

**Comment by LionelColaso** [comment]
@JinJanODWan @Skydea777 
if you can ping me on [RimSort Discord ](https://discord.gg/U8veTPVw) i would love to help and get the issue fixed

**Comment by JinJanODWan** [comment]
I am afraid I won't be doing anything on Discord.  I'd be happy to give you more details here.

**Comment by Skydea777** [comment]
<img width="944" height="302" alt="Image" src="https://github.com/user-attachments/assets/e407a563-766c-4fb7-a216-440cc5d8f1e4" />

Again, I completely Rebuild the Mod List.
I deleted the game and all the mods, all Optimized Images, regardless of everything.

Nearly every time I restart RimSort it seemingly thinks that a mod is missing! Pretty much never it uses the correct version of the Mod in Question with the current 1.6 or more then half of the time the mod is missing completely. (Not Found) Sometimes not even the Package ID is being shown which is especially great considering the size of the ModList.

Then even after re subscribing everything and starting RimSort multiple times (with the obligatory Wait times and even steam client restarts) I start the game, wait the 40 Minutes it takes to load up... HUZZA a new Mod is suddenly missing from the Mod List it was last saved.

I cannot explain how many hours I am wasting here troubleshooting, I am working in IT and such things irk me, that is totally uncool.

It also is not always just 2 or 3 mods...
I had one time where 32. **THIRTY TWO** Mods where gone, naturally only 3 with the correct Mod linked and more then half missing.

Such a grand time.

**Comment by Patryk-Malinowski** [comment]
Sometimes Steam fails to redownload the resubscribed mods and you start getting those missing mod errors.

I am seeing the `Mod Downloaded` field being set to 1970. I'll look into this further.

**Comment by Patryk-Malinowski** [comment]
@JinJanODWan @Skydea777  Regarding any missing mods, have you tried running Steam validation on RimWorld in an attempt to redownload all workshop mods? I would have expected redownloading RimWorld to sort that issue out for you @Skydea777 but maybe validation would help?

> Rimsort found _Alpha Bees_ to be out of date. I clicked update all button. As soon as Rimsort refreshes, _Retextured! - Recycle This_ is missing. I have to manually unsubscribe and resubscribe in Steam Workshop to get Rimsort to not see it as an _invalid item_ in my list.

Also I have not been able to reproduce a random mod missing when updating another mod. Will keep trying.

**Comment by Skydea777** [comment]
As I said, multiple times.
Manually Deletion.
Using RimSorts "Cleanup" Function on Mods and Game Files.
Checking File Consistency after Restarting Steam and waiting a couple of Minutes.
Everything a normal user does not do. As I said, I work in IT, I know the pitfalls when Programming something and such ... ""curious""... ""features"" emerge.

It is just so endless Frustrating because the few hours of Free Time I have in the week are wasted with Bug Hunting and loading bars.... oh wait... just like at work. I hope you understand why I am frustrated because of this and just to mention it, I do not blame anyone for this, this is just frustration against the world in general :).

EDIT.:
Right now, each time I click "Refresh" RimSort deceits to other Mods are missing. Why does this keeps happening.... right till "refresh" the mods are still there and the mod is still subscribed to.

**Comment by manilo81395** [comment]
Same Issue.
Version:1.0.52.
Regarding the issue where mods disappear even with Steam's own updates, random mods  be deleted.

**Comment by LionelColaso** [comment]
i am starting to wonder if the issue is with steam itself since I have rechecked the source multiple times and could not find the issue and the issue does not happen with steamcmd only with steam and RimSort only sends resubscribe command along with publishfieldid to steam and steam does the updating 
if you can try updating with steam without RimSort and you still have this issue then its a bug with steam and not RimSort
I cant test since i down own the game on steam so hopefully @Patryk-Malinowski you are able to test this

**Comment by JinJanODWan** [comment]
> [@JinJanODWan](https://github.com/JinJanODWan) [@Skydea777](https://github.com/Skydea777) Regarding any missing mods, have you tried running Steam validation on RimWorld in an attempt to redownload all workshop mods? I would have expected redownloading RimWorld to sort that issue out for you [@Skydea777](https://github.com/Skydea777) but maybe validation would help?
> 
> > Rimsort found _Alpha Bees_ to be out of date. I clicked update all button. As soon as Rimsort refreshes, _Retextured! - Recycle This_ is missing. I have to manually unsubscribe and resubscribe in Steam Workshop to get Rimsort to not see it as an _invalid item_ in my list.
> 
> Also I have not been able to reproduce a random mod missing when updating another mod. Will keep trying.

Missing mods had to be manually unsubbed and resubbed before being downloaded.

**Comment by JinJanODWan** [comment]
> i am starting to wonder if the issue is with steam itself since I have rechecked the source multiple times and could not find the issue and the issue does not happen with steamcmd only with steam and RimSort only sends resubscribe command along with publishfieldid to steam and steam does the updating if you can try updating with steam without RimSort and you still have this issue then its a bug with steam and not RimSort I cant test since i down own the game on steam so hopefully [@Patryk-Malinowski](https://github.com/Patryk-Malinowski) you are able to test this

I haven't had any issues since I stopped using Rimsort's update buttons.  I now manually update from Steam workshop directly if something is out of date and haven't had any disappearing mods since.  If the issue lies with SteamCMD not playing nice then so be it.  I can still use Rimsort to check and compare, save and load, and sort mod lists, which still work way better than other options.

**Comment by Skydea777** [comment]
After the latest Updates I have some Frustrations.
First, it installed itself with the Update to the C: Drive instead of the Custom Location I defined, so that is fucked.
Had to uninstall and reinstall it to be alt to actually update it via the .msi File.

Then after the first rounds of updates, it immediately again failed with the cursed Error.

The first Updates it found and tried to Download with Steam (I do not think that worked, to short.):

<img width="2510" height="1210" alt="Image" src="https://github.com/user-attachments/assets/6d4ee641-1dbc-4cbe-ad4d-425f8e9a21ba" />

Then "refresh" and (Yes the Downloads where Finished in Steam):

<img width="1797" height="1285" alt="Image" src="https://github.com/user-attachments/assets/9f6c1f76-b0f0-412c-88b1-7e3d8214cc07" />

As you can see it AGAIN deleted Mods that where there because I used them just minutes ago.
And it """found""" suddenly even more Updates.

Something with these functions is absolutely wrong.

Also this is the Mod Update List after the """update""":

<img width="2498" height="1078" alt="Image" src="https://github.com/user-attachments/assets/f0f265c9-78fa-4a62-aa07-de790bc222d5" />


As you can see it updated what.. 4 Mods and deleted 9 ? COME ON.

And after running these Updates?
It again only downloaded 2 Mods and deleted even more.
RimSort is NOT USABLE to Update Mods:

<img width="1229" height="635" alt="Image" src="https://github.com/user-attachments/assets/c59bdc2e-acf6-4409-afd7-f76f80fe6c74" />

**Comment by LionelColaso** [comment]
Can anyone conform if this issue still exists on latest version 1.0.59

**Comment by Skydea777** [comment]
I am on it, since 1.0.57 or 1.0.58 we have long... "Scanning mod sources and populating metadata..."

<img width="407" height="619" alt="Image" src="https://github.com/user-attachments/assets/f5d69622-51c9-4687-9e94-9cb7c8ed12de" />

Just wanted to mention it, this can take... "a while" to say it bluntly.

Okay. so it started with missing Mods:

<img width="949" height="664" alt="Image" src="https://github.com/user-attachments/assets/21c1abf1-a2bd-4bc4-887c-83ae34f0f723" />

And has 18 Updates to do via Steam Client, ok?

<img width="949" height="664" alt="Image" src="https://github.com/user-attachments/assets/df9fd3b0-a670-4938-b481-00957fb35d4e" />

I clicked on "Update with Steam Client" and... absolutely nothing happened.
So I hit "Refresh" again, got the two missing mods again, tried to "Update with Steam Client" a second time and nothing.
So I am Sub / Unsubbing to the missing mods. (Hitting the buttons only after Steam finished working its stuff.

Then "Refresh" again. -> Update (After selecting All)

And it looks like it only Updated two of the 18 Mods.. while looking at Steam.
Lets hit "Refresh".

<img width="949" height="664" alt="Image" src="https://github.com/user-attachments/assets/da04a45a-af49-4c19-b4e3-bd06f87f77a0" />

18/18.

And two more missing Mods:

<img width="949" height="664" alt="Image" src="https://github.com/user-attachments/assets/f292f242-b83f-470a-8f6d-7f8a9dab89ca" />

**Comment by LionelColaso** [comment]
@Skydea777 i need it tested with v1.0.59 since I have rewritten all the things and rechecked all places where delete or ACF file is touched

**Comment by Skydea777** [comment]
@LionelColaso 

<img width="265" height="36" alt="Image" src="https://github.com/user-attachments/assets/e7c0f0ba-3c0b-4561-a6cc-ca2ef47401ef" />

Really ? ^^
I can read ;)

**Comment by LionelColaso** [comment]
> [@LionelColaso](https://github.com/LionelColaso)
> <img alt="Image" width="265" height="36" src="https://private-user-images.githubusercontent.com/156956074/523360407-e7c0f0ba-3c0b-4561-a6cc-ca2ef47401ef.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUwNTA5MTUsIm5iZiI6MTc2NTA1MDYxNSwicGF0aCI6Ii8xNTY5NTYwNzQvNTIzMzYwNDA3LWU3YzBmMGJhLTNjMGItNDU2MS1hNmNjLWNhMmVmNDc0MDFlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIwNlQxOTUwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmM4MzFmZGUzNTZmZmFjNGU3MzcxMmI2MTg4ZmM4YWNhM2M0ZWFiYmFmY2IwMTNlMWM5YjY4ODM1ZTdhMWJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Uw8N2hOtiaORop3MDclt1mUKjJF4jW_NqAy9aE3E_9k">
> 
> Really ? ^^ I can read ;)

Would it be possible to see screenshot of location settings

**Comment by Skydea777** [comment]
Yeah, soon....

<img width="1440" height="943" alt="Image" src="https://github.com/user-attachments/assets/b9663e15-8d59-40f9-9ff3-b9a999859607" />

**Comment by LionelColaso** [comment]
I literally have 2000 mods and i never noticed any slowdown 
how many mods or are u using a HDD

<img width="1282" height="794" alt="Image" src="https://github.com/user-attachments/assets/1f2d5e42-3034-464f-8d0b-9c7004624d02" />

**Comment by Skydea777** [comment]
Two NVME SSDs. (Not the Shit kind.)
Rimworld and its Mods on the Second SSD.

<img width="608" height="69" alt="Image" src="https://github.com/user-attachments/assets/a8c71eb2-6301-4d68-8941-084bf0373d52" />
Stuck at "Checking Steam Workshop for Mod updates."
Still waiting and well... Oh it must be your Internet!
1GBit Fibre. Yes I am also trying to use an VPN or no VPN, no difference.

It must be your [Enter Reason] why mods ...

I reinstalled it the last weeks multiple times, MULTIPLE TIMES, different ways, Local Mods, Steam CMD only and so on....

Have to restart it again, crashed again.

EDIT:
WELP, SHITS FUCKED.
I think I will need to wait the timeout... out.
Will take a while.

EDIT 2:
Ah that explains it, I have no Internet clearly:

<img width="510" height="145" alt="Image" src="https://github.com/user-attachments/assets/49771208-db85-4cbf-bd7b-b766f079f1cd" />
I am using Pidgeons over IP to send this Edit'ed message to Github.

**Comment by Skydea777** [comment]
@LionelColaso 

Here are the Location Settings:

<img width="947" height="712" alt="Image" src="https://github.com/user-attachments/assets/1d72b340-db9b-4344-8c39-db57a1af03c7" />

C:\
and
D:\
Are the NVME SSD's
All Database's are Github, but also tried to create my own Workshop Database, but the issues remained identical.

**Comment by Skydea777** [comment]
@LionelColaso 
Just wanted to mention something, I do think that somehow the Steam API that talks with the Steam Client must be fucking everything up. (Pardon my language).
As we have seen, removal of installed and existing mods, executing Updates but for the wrong mods and not as it was before for all of the mods you have chosen in the Menu, I sadly do not know how you guys are """talking""" with the Steam Client to trigger the needed Updates, but I have the feeling that somewhere there must be the Issue, because I have put so many hours into this problem...

(What it does not explain is why missing mods are not found in the Workshop Database even if they where previously updated by it and so the Name, ID, etc. is known, why it cannot "find" them, and if they find them they often list only old Versions.)

**Comment by LionelColaso** [comment]
can you try 
1) Disable acf logreader 
2) restart rimsort  
3) try updating mods using RimSort
I just want to check if its not the one causing the issue 

<img width="1282" height="794" alt="Image" src="https://github.com/user-attachments/assets/29a4ae3d-877f-4737-86fe-3d0deb65fc0c" />

**Comment by Skydea777** [comment]
**### *sigh***
@LionelColaso 

- Update to 1.0.61.
- ACF Reader Disabled
- Internet Connection is On as I am working remote and see that I am Online.
- Starting RimSort.
- Steam API Timeout.
- "Refresh" -> Updates are there:
- 

<img width="947" height="631" alt="Image" src="https://github.com/user-attachments/assets/46a0f367-eba8-4c0b-a4db-8b376f37c244" />

- So I am running the Update, just one of the Mods gets its Update.
- Refresh... somehow even worse, how is this fucking possible, excuse my language but I am beyond frustrated:
- 

<img width="1232" height="755" alt="Image" src="https://github.com/user-attachments/assets/f4b9edf2-da61-4fbb-a91f-f52b811e36ca" />

- And as you can see **ONE** mod got updated and **SEVEN** updates were deleted.
- And even still it cannot even see all the Mods existing...

**Comment by Skydea777** [comment]
Sorry had to finish my Work Shift.
@LionelColaso 

Retested, Version 1.0.62:
After Starting the new Package ID Check started.
Only Github / Local Mods where found (which is 100% correct) and I added them to the Ignore list.
Stopped Rimsort waited a Minute and started it again.

Disabled ACF Log Reader, Ran Refresh, Updated the three mods, waited for it to complete, waited a Minute aaaaand:

<img width="1435" height="691" alt="Image" src="https://github.com/user-attachments/assets/e19329cf-ba82-4c3a-9702-1a969bafcba5" />

Deleted 2 mods again and updated 0 Mods again.

Absolutely the same as always.

So I activated the "ACF Reader" again, noticing (Via RimSort Log) that it constantly searches the File.
And this seems to lead to the Issue with the "Are you connect to the Internet" as I think when an ACF Scan is running and the new one is added behind it, the combined time it takes to read and parse the file is enough for it to run into an TimeOut.

Anyway.
Again -> Select all, Update with Steam Client.
Steam Client is doing """""something""""" but certainly not updating (Resubscribing) the 6 / 7 Mods I have chosen in the Update Menu.

<img width="291" height="119" alt="Image" src="https://github.com/user-attachments/assets/ec1b2d79-ffb0-4d2d-a6be-9a339e5d2b3a" />

Upon starting the Update:
[INFO][2025-12-12 22:24:39][7560][MainThread][acf_log_reader][load_acf_data][1291] : Starting ACF data loading.
[INFO][2025-12-12 22:25:09][7560][MainThread][acf_log_reader][load_acf_data][1291] : Starting ACF data loading.
[INFO][2025-12-12 22:25:39][7560][MainThread][acf_log_reader][load_acf_data][1291] : Starting ACF data loading.
[INFO][2025-12-12 22:26:08][7560][Dummy-3806][main_content_panel][_do_steamworks_api_call][2221] : Received Steamworks API instruction: ['resubscribe', [2260097569, 3536708812, 3610093707, 3614695123, 3613814532]]
[INFO][2025-12-12 22:26:08][7560][Dummy-3806][main_content_panel][_do_steamworks_api_call][2249] : Creating Steamworks API process with instruction ['resubscribe', [2260097569, 3536708812, 3610093707, 3614695123, 3613814532]]
[INFO][2025-12-12 22:26:09][7560][MainThread][acf_log_reader][load_acf_data][1291] : Starting ACF data loading.
[INFO][2025-12-12 22:26:19][7560][MainThread][acf_utils][refresh_acf_metadata][97] : Successfully parsed Steam client appworkshop.acf metadata from: D:\Program Files (x86)\Steam\steamapps\workshop\appworkshop_294100.acf
[INFO][2025-12-12 22:26:19][7560][MainThread][acf_utils][refresh_acf_metadata][97] : Successfully parsed Steam client appworkshop.acf metadata from: D:\Program Files (x86)\Steam\steamapps\workshop\appworkshop_294100.acf
[INFO][2025-12-12 22:26:29][7560][MainThread][acf_utils][refresh_acf_metadata][97] : Successfully parsed Steam client appworkshop.acf metadata from: D:\Program Files (x86)\Steam\steamapps\workshop\appworkshop_294100.acf
[INFO][2025-12-12 22:26:29][7560][MainThread][acf_utils][refresh_acf_metadata][97] : Successfully parsed Steam client appworkshop.acf metadata from: D:\Program Files (x86)\Steam\steamapps\workshop\appworkshop_294100.acf
[INFO][2025-12-12 22:26:39][7560][MainThread][acf_log_reader][load_acf_data][1291] : Starting ACF data loading.
[INFO][2025-12-12 22:26:40][7560][MainThread][acf_log_reader][fetchMore][434] : Fetched 1000 more entries, total loaded: 1000
[INFO][2025-12-12 22:26:40][7560][MainThread][acf_log_reader][fetchMore][434] : Fetched 679 more entries, total loaded: 1679
[INFO][2025-12-12 22:26:40][7560][Dummy-3810][acf_log_reader][run][318] : Loaded mod name for PFID 3300291918: [OA]Ratkin Gene Expand
**[...] Many more acf_log_reader entries [...]**
[INFO][2025-12-12 22:26:53][7560][Dummy-3811][acf_log_reader][run][318] : Loaded mod name for PFID 3531074246: Chougou Mechs
[INFO][2025-12-12 22:26:53][7560][Dummy-3810][acf_log_reader][run][323] : Loaded mod path for PFID 3531074246: D:\Program Files (x86)\Steam\steamapps\workshop\content\294100\3531074246
[INFO][2025-12-12 22:26:53][7560][Dummy-3811][acf_log_reader][run][318] : Loaded mod name for PFID 3001533648: [LittleFairy Addon]WishedWorld Technology
[INFO][2025-12-12 22:26:53][7560][Dummy-3810][acf_log_reader][run][323] : Loaded mod path for PFID 3001533648: D:\Program Files (x86)\Steam\steamapps\workshop\content\294100\3001533648

It.. just stops? Not one Entry about talking with the Steam API, seeing any changes or anything?
Instead 16 seconds later...
[INFO][2025-12-12 22:27:09][7560][MainThread][acf_log_reader][load_acf_data][1291] : Starting ACF data loading.
[INFO][2025-12-12 22:27:10][7560][MainThread][acf_log_reader][fetchMore][434] : Fetched 1000 more entries, total loaded: 1000
[INFO][2025-12-12 22:27:10][7560][MainThread][acf_log_reader][fetchMore][434] : Fetched 677 more entries, total loaded: 1677
[INFO][2025-12-12 22:27:10][7560][Dummy-3810][acf_log_reader][run][323] : Loaded mod path for PFID 3300291918: D:\Program Files (x86)\Steam\steamapps\workshop\content\294100\3300291918
[INFO][2025-12-12 22:27:10][7560][Dummy-3811][acf_log_reader][run][318] : Loaded mod name for PFID 3300291918: [OA]Ratkin Gene Expand
**[...] Many more acf_log_reader entries [...]**

Anyway it starts reading the acf file again and again.

And as I said, the Downloads are never correctly triggered, instead somehow, sometimes and way more often then welcome it deletes mods?

I am tired Boss.

**Comment by LionelColaso** [comment]
I Tested steam downloads and updates
for some reason, steam sometimes does not initiate downloads when cmd is sent
if the cmd is repeated then it starts download

in short steam sometimes does not respond to the command sent by RimSort
i will try to improve this

the missing random mods i am still checking 
hopefully i will find and fix the issue soon

**Comment by Skydea777** [comment]
Just wanted to Mention, no change with 1.0.63.
Still the same Issue with non updating mods and then missing mods.

EDIT:
Well, okay this is new....

<img width="932" height="432" alt="Image" src="https://github.com/user-attachments/assets/2d0226eb-c295-4b74-9124-63adcad8efa7" />

Well this is new?
I never subscribed to this Mod?


Is it the same Issue like with this Mod?

<img width="991" height="863" alt="Image" src="https://github.com/user-attachments/assets/533b9ab7-5bbc-4292-ab64-c6000d8b7912" />

https://steamcommunity.com/sharedfiles/filedetails/?id=1160612275

<img width="697" height="255" alt="Image" src="https://github.com/user-attachments/assets/9a70ca0d-cd41-49b0-b739-5e0078dc9b1b" />

**Comment by LionelColaso** [comment]
> Just wanted to Mention, no change with 1.0.63. Still the same Issue with non updating mods and then missing mods.
> 
> EDIT: Well, okay this is new....
> <img alt="Image" width="932" height="432" src="https://private-user-images.githubusercontent.com/156956074/528894203-2d0226eb-c295-4b74-9124-63adcad8efa7.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjYyNTcxODksIm5iZiI6MTc2NjI1Njg4OSwicGF0aCI6Ii8xNTY5NTYwNzQvNTI4ODk0MjAzLTJkMDIyNmViLWMyOTUtNGI3NC05MTI0LTYzYWRjYWQ4ZWZhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIyMFQxODU0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDM1MmI2OTkyZjc0MGY1MmY2MzJkZjhkZWY5MmZjNDExMjdmMzBlZDE0YzE0OThiNWE5Zjk4MjZlYmM5YTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oNrDG9r5RyFUhqUYk_yEyRWTm5iGPfjVOA8hAgL9pHU">


That is RimSort complaining that the mod not having a package id (you can see the missing.packageid) tag also read the description in the window the publishfieldid is just a suggestion for mod redownload matching the name

**Comment by Skydea777** [comment]
@LionelColaso 
Ah, perhaps you don't know.
I do not mean the Windows initself, I mean the amount of Published File IDs and that I have never seen the Mod before and never have subscribed to it, but that is not the whole Issue.

Sometimes, somehow, the mod with the Butcher Knife suddenly appears out of the Blue for Users of RimSort complaining that exactly THIS Mod is missing... but I and others have never subscribed to this "Buther Knife" Mod, in the same way I have never ever subscribed to the "Turbolaser Turret"-Mod.

**Comment by LionelColaso** [comment]
@Skydea777 can you try build from https://github.com/RimSort/RimSort/pull/1623

**Comment by Skydea777** [comment]
@LionelColaso @cebarks 
Jup tried it, showing Updates but Upon triggering the Updates with "Steam Client" nothing actually happens.
I  repeated this two more times, but Steam Client remained unresponsive and did not initiate any Updates.

After closing Rimworld, I waited an additional Minute and Steam Updated Rimworld, if this is just a coincidence I can not tell, but upon restarting no Mod Updates can be found.
I will have to wait a bit for new Updates to trickle in to Update what is happening on my end.
But right now as I said, Updates are not triggered Immediately.

But have to say the Logging is working nice:
`[INFO][2025-12-21 11:29:59][33312][MainThread][metadata][refresh_workshop_timestamps_via_steamworks][1850] : Refreshed timestamp for HugsLib (PFID: 818773962): old=1766312786 (2025-12-21 11:26:26), new=1752434318 (2025-07-13 21:18:38), delta=-13878468s (-160.6 days)
[INFO][2025-12-21 11:29:59][33312][MainThread][metadata][refresh_workshop_timestamps_via_steamworks][1850] : Refreshed timestamp for [FSF] Growable Grass (PFID: 817350064): old=1766312786 (2025-12-21 11:26:26), new=1761599314 (2025-10-27 22:08:34), delta=-4713472s (-54.6 days)
[INFO][2025-12-21 11:29:59][33312][MainThread][metadata][refresh_workshop_timestamps_via_steamworks][1850] : Refreshed timestamp for Humanoid Alien Races (PFID: 839005762): old=1766312786 (2025-12-21 11:26:26), new=1762608804 (2025-11-08 14:33:24), delta=-3703982s (-42.9 days)
[INFO][2025-12-21 11:29:59][33312][MainThread][metadata][refresh_workshop_timestamps_via_steamworks][1850] : Refreshed timestamp for Remove Tutorial Button (PFID: 781505663): old=1766312786 (2025-12-21 11:26:26), new=1749935057 (2025-06-14 23:04:17), delta=-16377729s (-189.6 days)
[INFO][2025-12-21 11:29:59][33312][MainThread][metadata][refresh_workshop_timestamps_via_steamworks][1850] : Refreshed timestamp for EdB Prepare Carefully (PFID: 735106432): old=1766312786 (2025-12-21 11:26:26), new=1754245078 (2025-08-03 20:17:58), delta=-12067708s (-139.7 days)
[INFO][2025-12-21 11:29:59][33312][MainThread][metadata][refresh_workshop_timestamps_via_steamworks][1850] : Refreshed timestamp for MinifyEverything (PFID: 872762753): old=1766312786 (2025-12-21 11:26:26), new=1755347385 (2025-08-16 14:29:45), delta=-10965401s (-126.9 days)
[INFO][2025-12-21 11:29:59][33312][MainThread][metadata][refresh_workshop_timestamps_via_steamworks][1850] : Refreshed timestamp for Achtung! (PFID: 730936602): old=1766312786 (2025-12-21 11:26:26), new=1756912877 (2025-09-03 17:21:17), delta=-9399909s (-108.8 days)
[INFO][2025-12-21 11:29:59][33312][MainThread][metadata][refresh_workshop_timestamps_via_steamworks][1850] : Refreshed timestamp for Simple sidearms (PFID: 927155256): old=1766312786 (2025-12-21 11:26:26), new=1755068836 (2025-08-13 09:07:16), delta=-11243950s (-130.1 days)
[INFO][2025-12-21 11:29:59][33312][MainThread][metadata][refresh_workshop_timestamps_via_steamworks][1850] : Refreshed timestamp for Better Workbench Management (PFID: 935982361): old=1766312786 (2025-12-21 11:26:26), new=1754468345 (2025-08-06 10:19:05), delta=-11844441s (-137.1 days)
[INFO][2025-12-21 11:29:59][33312][MainThread][metadata][refresh_workshop_timestamps_via_steamworks][1850] : Refreshed timestamp for Dubs Bad Hygiene (PFID: 836308268): old=1766312786 (2025-12-21 11:26:26), new=1753129491 (2025-07-21 22:24:51), delta=-13183295s (-152.6 days)
[INFO][2025-12-21 11:29:59][33312][MainThread][metadata][refresh_workshop_timestamps_via_steamworks][1850] : Refreshed timestamp for Dubs Skylights (PFID: 833899765): old=1766312786 (2025-12-21 11:26:26), new=1752536709 (2025-07-15 01:45:09), delta=-13776077s (-159.4 days)
[INFO][2025-12-21 11:29:59][33312][MainThread][metadata][refresh_workshop_timestamps_via_steamworks][1850] : Refreshed timestamp for WeaponStats (PFID: 974066449): old=1766312786 (2025-12-21 11:26:26), new=1752246321 (2025-07-11 17:05:21), delta=-14066465s (-162.8 days)
[INFO][2025-12-21 11:29:59][33312][MainThread][metadata][refresh_workshop_timestamps_via_steamworks][1874] : Steamworks timestamp refresh complete: 1450 updated, 0 failed out of 1450 Workshop mods
[INFO][2025-12-21 11:29:59][33312][MainThread][main_content_panel][_do_check_for_workshop_updates][2132] : Refreshed timestamps for 1450 Workshop mods (0 failed)
[INFO][2025-12-21 11:29:59][33312][Dummy-19][metadata][query_workshop_update_data][3225] : Querying Steam WebAPI for SteamCMD/Steam mod update metadata
[INFO][2025-12-21 11:30:19][33312][MainThread][mod_utils][filter_eligible_mods_for_update][173] : Update detection summary: 0 eligible for update, 1430 up-to-date, 0 missing internal timestamp, 20 missing external timestamp (Total Workshop mods checked: 1450)
[WARNING][2025-12-21 11:30:19][33312][MainThread][workshop_mod_updater_panel][__init__][81] : No mods with updates available.
[INFO][2025-12-21 11:30:19][33312][MainThread][mod_utils][filter_eligible_mods_for_update][173] : Update detection summary: 0 eligible for update, 1430 up-to-date, 0 missing internal timestamp, 20 missing external timestamp (Total Workshop mods checked: 1450)`

**Comment by LionelColaso** [comment]
Can you guys test https://github.com/RimSort/RimSort/releases/tag/Edge

**Comment by Skydea777** [comment]
Done and Done.

Same behavior.

`
[INFO][2025-12-21 19:48:44][11884][MainThread][acf_utils][refresh_acf_metadata][97] : Successfully parsed Steam client appworkshop.acf metadata from: D:\Program Files (x86)\Steam\steamapps\workshop\appworkshop_294100.acf
[INFO][2025-12-21 19:48:44][11884][MainThread][acf_utils][refresh_acf_metadata][97] : Successfully parsed Steam client appworkshop.acf metadata from: D:\Program Files (x86)\Steam\steamapps\workshop\appworkshop_294100.acf
[INFO][2025-12-21 19:48:55][11884][Dummy-18][main_content_panel][_do_steamworks_api_call][2290] : Received Steamworks API instruction: ['resubscribe', [3516409503, 3596077324]]
[INFO][2025-12-21 19:48:55][11884][Dummy-18][main_content_panel][_do_steamworks_api_call][2325] : Creating Steamworks subscription task with instruction ['resubscribe', [3516409503, 3596077324]]
[INFO][2025-12-21 19:48:55][11884][Dummy-19][main_content_panel][run][117] : [STEAM_THREAD] Executing resubscribe for 2 mods
[INFO][2025-12-21 19:48:55][11884][Dummy-19][wrapper][_handle_subscription_action][186] : Handling Steam subscription action: resubscribe
[INFO][2025-12-21 19:48:55][11884][Thread-20 (_callbacks)][wrapper][_callbacks][326] : Steamworks loaded!
[INFO][2025-12-21 19:48:59][11884][Thread-20 (_callbacks)][wrapper][_callbacks][331] : 4 callback(s) received. Ending thread...
[INFO][2025-12-21 19:48:59][11884][Dummy-19][wrapper][_finish_callbacks][306] : Callback thread completed for operation: resubscribe
[INFO][2025-12-21 19:48:59][11884][Dummy-19][main_content_panel][run][132] : [STEAM_THREAD] Completed resubscribe for 2 mods
[INFO][2025-12-21 19:48:59][11884][Dummy-18][main_content_panel][_do_steamworks_api_call][2340] : Subscription thread completed
`

Only after Ending RimSort the Triggered Updates are executed:

<img width="1336" height="226" alt="Image" src="https://github.com/user-attachments/assets/94150d8f-e4ac-4eca-ba89-1ef174c34745" />



#################

Just to mention this is a way preferable behavior then before, that has done no Updating and sometimes deleting Mods.

Sadly as it is Sunday not many Updates are released so i cannot test this multiple times one after the next, so I cannot state if these changes will also remove the Problem with removed mods.
(But secretly I am really thinking that it is fixed. No mod was deleted since the 1.0.64 Versions.)

################

@LionelColaso 

I still have the "ACF Logreader" Disabled, should I keep it this way?

**Comment by cebarks** [comment]
@Skydea777 Do you have downloads disabled in steam while a game is running? If you can try updating the mods without the game running, that could very well be the problem.

**Comment by Skydea777** [comment]
@cebarks 
Nope, I have gone to this Trial a couple of times as I tried to find the reason for this odd behavior of RimSort, no Download Speed Limitation and Downloading while Game is Running active. (Allowed not Disabled)

And Rimworld Update Priority is set to Update Immediately.

**Comment by cebarks** [comment]
Have you tried it with the game not running?

**Comment by Skydea777** [comment]
@cebarks 
Is... this some kind of Joke?
Why would I run the game if I want to Update it?
No you misunderstood me, I mean the setting, if another Game is Running, any other Game, Updates are allowed, always.

**Comment by Skydea777** [comment]
@LionelColaso & @cebarks 

I found something.
Upon starting RimSort it checks for Updates (if activated) what I noticed is:

<img width="1190" height="656" alt="Image" src="https://github.com/user-attachments/assets/0c150039-8d63-41db-a7ab-e16afde1cca9" />

In the Background the Game is """"**started**"""".
But after the check the game is never **closed** / **stopped**!
Only after RimSort is closed down / application exited, the game "RimWorld" is released.

Which explains why the Updates are not triggered, only after RimWorld Process if again not in this "false" _**running**_ state the Updates are triggered.

**Comment by cebarks** [comment]
> [@cebarks](https://github.com/cebarks) Is... this some kind of Joke? Why would I run the game if I want to Update it? No you misunderstood me, I mean the setting, if another Game is Running, any other Game, Updates are allowed, always.

Sorry i definitely misunderstood then, this comment made me think you were trying to update your mods via RimSort while Rimworld was running: 
> After closing Rimworld, I waited an additional Minute and Steam Updated Rimworld, if this is just a coincidence I can not tell, but upon restarting no Mod Updates can be found.

**Comment by cebarks** [comment]
> [@LionelColaso](https://github.com/LionelColaso) & [@cebarks](https://github.com/cebarks)
> 
> I found something. Upon starting RimSort it checks for Updates (if activated) what I noticed is:
> <img alt="Image" width="1190" height="656" src="https://private-user-images.githubusercontent.com/156956074/529016440-0c150039-8d63-41db-a7ab-e16afde1cca9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjYzNTY0NzcsIm5iZiI6MTc2NjM1NjE3NywicGF0aCI6Ii8xNTY5NTYwNzQvNTI5MDE2NDQwLTBjMTUwMDM5LThkNjMtNDFkYi1hN2FiLWUxNmFmZGUxY2NhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIyMVQyMjI5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzYyNWYxNDg1NTZjODQ1ZjFmZWM0MzhjYTAyYmY1YjAyYmY4ZGQxNzBkOGY2YTE0M2Q4ZGVmMmIxMWU1MmFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HnKjGFXN2Bm9OJzTz-7Mgm8Dbmk7bqAVepGGrStbChY">
> 
> In the Background the Game is """"**started**"""". But after the check the game is never **closed** / **stopped**! Only after RimSort is closed down / application exited, the game "RimWorld" is released.
> 
> Which explains why the Updates are not triggered, only after RimWorld Process if again not in this "false" _**running**_ state the Updates are triggered.

Let me see if I can replicate this locally (although i'm on linux, not windows.)

**Comment by LionelColaso** [comment]
Can you guys try these versions
https://github.com/RimSort/RimSort/releases/tag/v1.0.44 

also use_this_instead database might not work with this version so you may have to turn it off
Best is to delete the settings.json or reset the settings so not to have unwanted issues

I am hoping for everything related to steam to be working on version v1.0.44

**Comment by Skydea777** [comment]
@LionelColaso & @cebarks 

So I tried it now for a couple of days, I only had one removed mod up until now, it looks with the new Download Variant in Version 1.0.64 Edge8 is solving the Missing Mod Issue and also the Inability of Downloading Mods (Albeit with the restriction that you need to close RimSort to execute the Updates).

So the only Issue that is still happening is the Issue that as soon as RimSort accesses RimWorlds Workshop (Steam) it is seemingly executed, but as anyone knows, a picture says more then thousands of words... but what.. about MOVING PICTURES!?



![Image](https://github.com/user-attachments/assets/14b05585-0a75-435a-9039-1245ef1fee50)

**Comment by cebarks** [comment]
So i've figured out what causes this behavior. It's because we use the steamworks api initialized via the rimworld app id. The only real solution would be to register RimSort as it's own independent steam app. 

It is a one-time $100 fee, but we could also distribute rimsort through steam (which may also allow us to bypass the macos gatekeeper? no sure i'll need to look into this). 

The only other less-ideal option I can come up with is to make sure we kill any steamworks instances as quickly and cleanly as possible. 

EDIT: after looking into this more, unfortunately the current behavior is the only option. the only way we can interface with the workshop like we do is by initializing steamworks with rimworld's app id.

Also random side note @Skydea777: is your background the DVD idle animation? that's so amazing I love it!

**Comment by LionelColaso** [comment]
Ok Guys some update
```
Good News
I am able to replicate the issue 

Bad News
I will fix it but not sure when since i am a bit busy but i will try fixing it on priority
```

**Comment by cebarks** [comment]
@LionelColaso It seems to be an issue with leaving partial mod directories when deleting a workshop mod. Did you come to the same conclusion?

I've got a change locally that as far as I can tell fixes this, I'm just polishing it up before committing to #1623.

**Comment by Skydea777** [comment]
Ah sad, the Download Change didn't make it to 1.0.64 :(

<img width="348" height="828" alt="Image" src="https://github.com/user-attachments/assets/2975d13d-cd4e-4145-b5fc-80c19c906236" />

**Comment by Skydea777** [comment]
Just to also add my comment from [Issue 1587](https://github.com/RimSort/RimSort/issues/1587)  it to this Issue:
@LionelColaso

[https://i.imgur.com/1uTF1Wd.gif](https://i.imgur.com/1uTF1Wd.gif)

**Comment by Skydea777** [comment]
@LionelColaso 
V1.0.66

I am truly sorry, we are now again at the exact same place that started this whole thread.

It startet AN Update, not all of them, instead, we are again at the stage that it deletes Mods, its Information and cannot find them anymore.

<img width="803" height="483" alt="Image" src="https://github.com/user-attachments/assets/e5e03959-32fc-4227-af79-77dee6a2f154" />

Multiple steps back from the Edge 8 1.0.64 Version (that I sadly lost so I cannot update my mods anymore.)

**Comment by LionelColaso** [comment]
I understand and working on the fix 
on latest v1.0.66 for example, RimSort is correctly sending the mods and steam also receives them correctly and registers it, but steam does not process it correctly (you can check the RimSort logs as well as steam mods subscription page if you want to check if steam registers RimSorts command or not)

**Comment by LionelColaso** [comment]
Finally Fixed in #1709

**Comment by Skydea777** [comment]
@LionelColaso 
This is absolutely not fixed?

<img width="940" height="743" alt="Image" src="https://github.com/user-attachments/assets/eec0d169-bf4d-4286-b8e7-9489b290020c" />

When I start here the Update with Steam Client, you just trigger a data integrity check, which takes with a large amounts of mods even with an nvme about half an hour?
That is not a fix, that is a Bandaid, we are not triggering Updates at all???

<img width="1045" height="94" alt="Image" src="https://github.com/user-attachments/assets/00c6bafa-cb2f-4e4e-8752-d408f524d9d3" />

**Comment by Skydea777** [comment]
@LionelColaso 

So it is the next morning, i restarted Rimsort and well look at that, even a missing mod.

<img width="945" height="937" alt="Image" src="https://github.com/user-attachments/assets/1c93caf5-7364-4390-be8c-5b2001d613e0" />

Sorry I cannot reopen the Issue as I do not have the permission to do that, but the Problem is as I said not solved.

**Comment by LionelColaso** [comment]
@Skydea777 it was a temp solution i have fixed it but not pushed the changes since i had to rewrite the behaviour i had to block the action

<img width="393" height="382" alt="Image" src="https://github.com/user-attachments/assets/89ec81d4-56e3-40e0-818b-096f65f2675c" />

**Comment by LionelColaso** [comment]
@Skydea777 can you try https://github.com/LionelColaso/RimSort/releases/tag/Edge

**Comment by Skydea777** [comment]
@LionelColaso 

It took quiet a while...

<img width="1000" height="117" alt="Image" src="https://github.com/user-attachments/assets/f51a6ae8-a74c-47af-a60e-fae83a58abfd" />

Congratulation, this is a solution that could work.


So, Facts:

- Resubscribing to a missing mods does **NOT** work.
- Engaging Updates does "**Fake**" start the game in the Rimworld Overview, killing it closes RimSort, after Update Finishes the game is not stopped and continues ""**running**"".
   This is the same behavior as the Last "Edge" Version you let me check some time ago where the Updates also worked, just as an heads up.
- So I had about **60 Updates**, it took a **long time** (a couple of minutes) for the Parsing of the Mods and whatever to run through, after it finished calculating its dark magic it send its stuff to steam and the downloads started, this also took quiet a while BUT, that is Steams Fault.
- After Restarting Steam, Rimsort ... MULTIPLE TIMES, running refreshes and so on and so on.
**### - IT WORKS - NO MISSING MODS - NO FAILED UPDATES**

I am sorry, I am a big dumb dumb and forgot to save the Log after the Updates before restarting multiple time... I forgor that they are being overwritten.

Thank You @LionelColaso .

**Comment by LionelColaso** [comment]
> [@LionelColaso](https://github.com/LionelColaso)
> 
> It took quiet a while...
> <img alt="Image" width="1000" height="117" src="https://private-user-images.githubusercontent.com/156956074/536390818-f51a6ae8-a74c-47af-a60e-fae83a58abfd.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njg1MDU3OTUsIm5iZiI6MTc2ODUwNTQ5NSwicGF0aCI6Ii8xNTY5NTYwNzQvNTM2MzkwODE4LWY1MWE2YWU4LWE3NGMtNDdhZi1hNjBlLWZhZTgzYTU4YWJmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDExNVQxOTMxMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzRlZjk1ZGM5ZWYwNmY5MTE2M2I3YmI3ZjVjZjE2OTNkODRiZDUxM2FmYjBhNDk3NGQ1YjUyZTQ5ZGU0YTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.a4OZxhMgyjOhK2haxLCO6r4Q1d3DqRBRt5-5jCjtFbU">
> 
> Congratulation, this is a solution that could work.
> 
> So, Facts:
> 
>     * Resubscribing to a missing mods does **NOT** work.
> 
>     * Engaging Updates does "**Fake**" start the game in the Rimworld Overview, killing it closes RimSort, after Update Finishes the game is not stopped and continues ""**running**"".
>       This is the same behavior as the Last "Edge" Version you let me check some time ago where the Updates also worked, just as an heads up.
> 
>     * So I had about **60 Updates**, it took a **long time** (a couple of minutes) for the Parsing of the Mods and whatever to run through, after it finished calculating its dark magic it send its stuff to steam and the downloads started, this also took quiet a while BUT, that is Steams Fault.
> 
>     * After Restarting Steam, Rimsort ... MULTIPLE TIMES, running refreshes and so on and so on.
>       **### - IT WORKS - NO MISSING MODS - NO FAILED UPDATES**
> 
> 
> I am sorry, I am a big dumb dumb and forgot to save the Log after the Updates before restarting multiple time... I forgor that they are being overwritten.
> 
> Thank You [@LionelColaso](https://github.com/LionelColaso) .

1) The build which I shared for you does one mod at a time, that's why it took time to complete since I just needed confirmation it works (I had tested it myself using resubscribe) which is the same behavior used for mod updates)
2) I have optimized it to be much faster than the version you tested once it's complete it could download the entire RimWorld workshop (50500) something in 7 hours, the version you tested it would take it about 15 hours (based on the measured performance) 
3) steam does not allow more than 15000 subscription
4) the real issue is steam does not process unsubscription request immediately it processes them as soon as RimSort is closed (so finding a workaround for that)

once i am finished my testing and have everything working, i will push the updated version 
just not sure should i push the current implementation and then push the optimized version or wait till the optimized version is done

**Comment by Skydea777** [comment]
Well @LionelColaso,
you could leave a note at latest release, with the Mention that Updating is currently bugged and there is a non supported Pre-pre-alpha Version out,
that is fixing this with drawbacks of an pre-pre-alpha Version and the guarantee that there will be bugs.
Then Link to a version you might me okay with to release in the meantime.
So you can work on your final version in peace and finish it in your own time when you are happy with it.

**Comment by LionelColaso** [comment]
> Well [@LionelColaso](https://github.com/LionelColaso), you could leave a note at latest release, with the Mention that Updating is currently bugged and there is a non supported Pre-pre-alpha Version out, that is fixing this with drawbacks of an pre-pre-alpha Version and the guarantee that there will be bugs. Then Link to a version you might me okay with to release in the meantime. So you can work on your final version in peace and finish it in your own time when you are happy with it.

For now pushing working one will push the optimized one later since it will need some backend work firest

**Comment by LionelColaso** [comment]
@Skydea777 if you want you can compare the previous version which i shared or https://github.com/RimSort/RimSort/releases/tag/v1.0.68 with https://github.com/LionelColaso/RimSort/releases/tag/Edge

**Comment by mrfunstuff** [comment]
this is still occurring in 1.0.76.

i am really not sure what logs to offer because this has nothing to do with rimworld itself.

**Comment by ColdTest-0** [comment]
This bug began happening to me today after not playing Rimworld for a few days. When I start Rimsort, it reports that anywhere from 10 to 60 mods are missing (over 1000 mods using Ferny's modpack). I use "select all" and "download with steam client" to download the missing mods. Some will be missing their published ID field, preventing them from being downloaded automatically. I resubscribe to those mods manually on the steam workshop. After putting the mods back in the modlist, I start rimworld. However, attempting to load a save reveals that a new batch of mods are missing. Refreshing or restarting Rimsort will verify this and prompt me to redownload those mods. I am unable to get in game or start rimsort without there being missing mods. I have been repeating this for a few hours.
