### ISSUE TITLE
FIXME: Game fails to launch properly / load the Steam API when using the Run command.

### ISSUE THREAD

**Issue by largemoron** [RimSort/RimSort#36]
- [x] Modify `_do_platform_specific_game_launch` to launch the game in it's own subprocess
- [x] Additionally, launch the game with the Steam API, if Steam is available.
- [x] Fix issue with frozen builds on MacOS/Windows

M1 Macbook air, OS: Ventura 13.2.1 

When using the Run command to launch the game I'll get the normal Rimworld planet screen with the ". . ." loading box, but when the dots change to "Loading Defs..." the screen turns black and it just hangs. I've left it untouched for up to 25 minutes and nothing happened. When launched from Steam it loads normally in only a few minutes.

Player.log attached. Here are some API-related lines that look relevant.  Steam is running, and the steam_appid.txt file is present in the correct location. 
[Player.log](https://github.com/oceancabbage/RimSort/files/10807516/Player.log)

```

[S_API FAIL] SteamAPI_Init() failed; no appID found.
Either launch the game from Steam, or put the file steam_appid.txt containing the correct appID in your game folder.
[Steamworks.NET] SteamAPI.Init() failed. Possible causes: Steam client not running, launched from outside Steam without steam_appid.txt in place, running with different privileges than Steam client (e.g. "as administrator") 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 39)

```

and here's the end of the rimsort log. doesn't look like there's anythimg useful in it.

```

[INFO][2023-02-22 11:51:53,241][26658][view.main_content_panel][actions_slot][239] : USER ACTION: received action run
[INFO][2023-02-22 11:51:53,242][26658][view.main_content_panel][_do_platform_specific_game_launch][288] : USER ACTION: launching the game
[INFO][2023-02-22 11:51:53,242][26658][view.game_configuration_panel][get_game_folder_path][747] : Responding with requested Game Folder: /Users/USERNAME/Library/Application Support/Steam/steamapps/common/Rimworld/
[INFO][2023-02-22 11:51:53,242][26658][view.main_content_panel][_do_platform_specific_game_launch][290] : Attempting to find the game in the game folder /Users/USERNAME/Library/Application Support/Steam/steamapps/common/Rimworld/
[INFO][2023-02-22 11:51:53,243][26658][view.main_content_panel][_do_platform_specific_game_launch][295] : Path to game executable for MacOS generated: /Users/USERNAME/Library/Application Support/Steam/steamapps/common/Rimworld/RimWorldMac.app
[INFO][2023-02-22 11:51:53,245][26658][view.main_content_panel][_do_platform_specific_game_launch][299] : Launching the game with subprocess Popen: /Users/USERNAME/Library/Application Support/Steam/steamapps/common/Rimworld/RimWorldMac.app with args: ``
[INFO][2023-02-22 11:51:53,286][26658][view.status_panel][actions_slot][57] : Displaying fading text for action: run
[INFO][2023-02-22 11:52:30,085][26658][main][<module>][119] : Exiting program

```

When launched with no mods at all it will make it to the title screen, but I'll get this Steam API error. 
<img width="666" alt="Screenshot 2023-02-22 at 5 18 13 PM" src="https://user-images.githubusercontent.com/99063144/220793796-8228a503-f07e-447c-9760-5a8c00ed3725.png">

**Comment by twstagg** [comment]
Fixed in [3faba04](https://github.com/oceancabbage/RimSort/pull/46/commits/3faba04d3fee6f411cd0892b6149cadf56de24e7)

**Comment by largemoron** [comment]
Not quite fixed. I posted about this in discord and something else is up with this.

Rather than launching the game and hanging at a black loading screen or throwing an API error if you reach the main menu, Run doesn't do anything now. On top of that, it appears to corrupt? the log file with this endlessly repeated red **nul**

<img width="1172" alt="Screenshot_2023-03-29_at_4 54 20_PM" src="https://user-images.githubusercontent.com/99063144/228699319-dd189ef8-e224-4c78-bc48-ff7554f79e78.png">

That's the whole 22.9mb log file as it appears in vscode when I try to open it after pressing Run.

**Comment by twstagg** [comment]
> Not quite fixed. I posted about this in discord and something else is up with this.
> 
> Rather than launching the game and hanging at a black loading screen or throwing an API error if you reach the main menu, Run doesn't do anything now. On top of that, it appears to corrupt? the log file with this endlessly repeated red **nul**
> 
> <img alt="Screenshot_2023-03-29_at_4 54 20_PM" width="1172" src="https://user-images.githubusercontent.com/99063144/228699319-dd189ef8-e224-4c78-bc48-ff7554f79e78.png">
> 
> That's the whole 22.9mb log file as it appears in vscode when I try to open it after pressing Run.

This is only present in pyinstaller build. Researching solutions.

**Comment by largemoron** [comment]
This has popped back up in v1.0.4.2

Doesn't appear to be anything in the logs after pressing launch. Tested (with steam running) on a 375 count mod pack I just put together and it gives me the endless black screen. With just the base game and expansions it loads to the main menu but throws up the steam API error. Both launch fine from Steam.

**Comment by twstagg** [comment]
This should be properly fixed in v1.0.5.2

There's still a weird error i'm going to debug further, but you can ignore it and your log/RimSort application/game launch will function normally.

**Comment by DurekuRyuu** [comment]
Good news!
It's back!

Also I'm getting weird text corruption or artifacting in the startup messages.
Like 'loading combat AI' is accented as much as possible and has lines through it and other unnecessary stuff.

Learning how to pull a log from this, as I'd like to do more to help.

Also it's occasionally removing all my mods from active and only having the vanilla stuff.

[RimSort.log](https://github.com/user-attachments/files/17237033/RimSort.log)

[Player.log](https://github.com/user-attachments/files/17237031/Player.log)

I've got it set to debug logging, so here's hoping this is actually helpful.

(Yes I am a madwoman using 600 some mods shhhh it launched when I used rimpy, but I've switched to this to use something open source that's up to date. Maybe it'll even make my abominable modlist run anything like well.)

**Comment by hk21702** [comment]
What version are you on right now? Did this start happening after a RimSort update?

**Comment by DurekuRyuu** [comment]
V1.0.10

I'm fairly sure this is a mod interaction issue, my mod list is nightmarish and I haven't exactly resolved the torrent of red errors I have.

**Comment by hk21702** [comment]
Hmm... If its new with this version with nothing else changed then it could be on our side. For the Steam API issue, just make sure you have steam open and you have steam integration enabled under advanced.

If this happens with RimPy as well then it is most likely some weird thing with your mods? The corruption is most likely something to do with your mods.

**Comment by DurekuRyuu** [comment]
Funny you should say that.
It doesn't happen with RimPy's sorting.
RimPy seems to disagree with the sorting decisions that RimSort uses, but that's no suprise.
![Rimsort sorting is different](https://github.com/user-attachments/assets/2333c154-4861-4cfd-8462-4efdd3f12d58)

I'll upload the load order and list with RimPy and Rimsort for comparison.
[modlists xmls.zip](https://github.com/user-attachments/files/17252097/modlists.xmls.zip)

So the RimSort-ed list causes this blackscreen forever issue, wheras the RimPy sorted list does not. Hopefully the pic of the error description from RimPy helps.

**Comment by hk21702** [comment]
In that case, it's just a load order issue. You have something that that needs to be loaded a certain way, but the rule isn't defined correctly. Technically this isn't RimSort fault, it's correctly applying all the rules it was given. It's just that the solution rimpy gave just happened to avoid the issue while RimSort did not. You'll need to just play around with your load order and the add the rule manually using the rules editor afterwards. You may also want to submit the rule to the community rules database to help others and report the issue to the authors so they can add it to their about file. 

Are you still having the steam Api not found thing? Unfortunately that's really the only thing I can help with here. Everything else seems like a load order issue.
