### ISSUE TITLE
Linux Crash on Start: ctypes has no attribute windll

### ISSUE THREAD

**Issue by WeaverThree** [RimSort/RimSort#844]
### Release Type

Self-Compiled

### Version

df7b597a1b03e0cf7fb740ba7fdab6cbacd78fb3

### Operating System

Nobara Linux (KDE)

### Relevant logs

Very short so pasted it below

### Describe the bug

When I try to build and run from commit df7b597a1b03e0cf7fb740ba7fdab6cbacd78fb3 (current as of this post) I get a fatal error dialog and this on the console:

```
AttributeError: module 'ctypes' has no attribute 'windll'
```

Same problem on two similar systems. 

Building and running from commit c70cf9f563e46f066127ac3291fbe194b51629c9 works fine.

### Additional context

Entire log file, since it's short. Command line dumps half of this:

```
[INFO][2025-05-02 23:28:38][1610924][MainThread][__main__][<module>][213] : Initializing RimSort application: Unknown version
[ERROR][2025-05-02 23:28:38][1610924][MainThread][__main__][main_thread][119] : The main application instantiation has failed with an uncaught exception:
[ERROR][2025-05-02 23:28:38][1610924][MainThread][__main__][main_thread][122] : Traceback (most recent call last):
  File "/home/.../Documents/RSTmp/RimSort/build/__main__.dist/__main__.py", line 98, in main_thread
  File "/home/.../Documents/RSTmp/RimSort/build/__main__.dist/app/controllers/app_controller.py", line 24, in __init__
  File "/home/.../Documents/RSTmp/RimSort/build/__main__.dist/PySide6-postLoad.py", line 43, in __init__
AttributeError: module 'ctypes' has no attribute 'windll'

[INFO][2025-05-02 23:28:38][1610924][MainThread][dialogue][show_fatal_error][234] : Showing fatal error box with input: [Fatal Error], [A fatal error has occurred!], [Please report the error to the developers.], [Traceback (most recent call last):
  File "/home/.../Documents/RSTmp/RimSort/build/__main__.dist/__main__.py", line 98, in main_thread
  File "/home/.../Documents/RSTmp/RimSort/build/__main__.dist/app/controllers/app_controller.py", line 24, in __init__
  File "/home/.../Documents/RSTmp/RimSort/build/__main__.dist/PySide6-postLoad.py", line 43, in __init__
AttributeError: module 'ctypes' has no attribute 'windll'
]
[INFO][2025-05-02 23:28:38][1610924][MainThread][dialogue][exec][270] : Showing base dialogue box with title: Fatal Error
[INFO][2025-05-02 23:28:39][1610924][MainThread][dialogue][exec][272] : Finished showing base dialogue box [Fatal Error] with result: 0
[INFO][2025-05-02 23:28:39][1610924][MainThread][__main__][main_thread][135] : Exiting application!
```

### Code of Conduct

I agree to follow this project's Code of Conduct

### Duplicate Issue Check

I've checked for similar issues and didn't find anything

### Wiki/FAQ Check

I've checked the Wiki for a solution and didn't find a solution

**Comment by LionelColaso** [comment]
Can you try directly the below by opening Terminal in the root of "RimSort" folder and run the commands all or as required and check if the app launches 

# git commands
git checkout main
git reset --hard
git pull -f --rebase

# create venv if you dont have it
python3 -m venv .

# activate venv if you are using it
source bin/activate

#  get all the requirements
pip install -r requirements.txt -r requirements_develop.txt

# run the distribute command without building the full app
python distribute.py --skip-build

# run RimSort (launch app) directly from source
python -m app

**Comment by LionelColaso** [comment]
The actual issue is with nuitka if you downgrade to 2.6.9 version or revert this commit build will be ok https://github.com/RimSort/RimSort/pull/842/files

**Comment by turol** [comment]
Latest release is also broken.

**Comment by Aftermath** [comment]
1.0.16 actually worked fine for me on Fedora 42, but 1.0.17 did me in.

**Comment by sounak-kun** [comment]
Having the same issue on MacOS, with version 1.0.17

**Comment by LionelColaso** [comment]
@Aftermath @sounak-kun @turol can you guys test the Edge build https://github.com/RimSort/RimSort/releases

**Comment by LionelColaso** [comment]
@WeaverThree can you update the source and recheck the issue should be fixed now

**Comment by turol** [comment]
Still broken with the same message.

**Comment by sounak-kun** [comment]
Can confirm, still having the same error message with the Edge build
Platform: MacOS

**Comment by LionelColaso** [comment]
Ok i Could replicate the issue
This  is due to the fact github actions using Nuitka main branch having version 2.7.2 
since github action currently  bypasses the set version of Nuitka 2.6.9 in the requirements_build.txt
manually building with 2.6.9 works fine but when building with 2.7.2 I could replicate the below error on both mac and linux builds
 `AttributeError: module 'ctypes' has no attribute 'windll'` 

i will open up a issue with Nuitka hopefully it will be fixed soon since the developer is actively developing
