### ISSUE TITLE
No internet connection error

### ISSUE THREAD

**Issue by yomato26** [RimSort/RimSort#955]
### Release Type

Compiled (Windows x86-64)

### Version

v1.0.21

### Operating System

Windows 11

### Describe the bug

On launch of v1.0.21 there are 3 popup windows for "No Internet Connection" tested reverting to .20 and this issue only presents in the new .21 version.

![Image](https://github.com/user-attachments/assets/61621271-16cd-410b-a9b4-024ada6a3cee)

### Code of Conduct

I agree to follow this project's Code of Conduct

### Duplicate Issue Check

I've checked for similar issues and didn't find anything

### Wiki/FAQ Check

I've checked the Wiki for a solution and didn't find a solution

**Comment by yomato26** [comment]
I have asked another user to validate this on the Linux build and they are having the same issue.

**Comment by oceanfrost** [comment]
Turn off the automatic update of the database in the advanced settings.

**Comment by yomato26** [comment]
> Turn off the automatic update of the database in the advanced settings.

Unfortunately didn't help if you mean this setting?

![Image](https://github.com/user-attachments/assets/9679f0c8-7eb8-4a31-b636-f832d9a7f49f)

**Comment by LionelColaso** [comment]
> > Turn off the automatic update of the database in the advanced settings.
> 
> Unfortunately didn't help if you mean this setting?
> 
> ![Image](https://github.com/user-attachments/assets/9679f0c8-7eb8-4a31-b636-f832d9a7f49f)

try disbling 

![Image](https://github.com/user-attachments/assets/c08680ac-d889-4372-8dfd-4952d473f653)

**Comment by yomato26** [comment]
So disabling this has shown the issue appears to be due to 3 items (given 3 of those errors on startup):

1. Check for updates on startup
2. Update database on startup (advanced settings)
3. ???

It doesn't appear to check workshop for mod updates either anymore.

**Comment by LionelColaso** [comment]
> So disabling this has shown the issue appears to be due to 3 items (given 3 of those errors on startup):
> 
>     1. Check for updates on startup
> 
>     2. Update database on startup (advanced settings)
> 
>     3. ???
> 
> 
> It doesn't appear to check workshop for mod updates either anymore.

i know what the issue is will push fix

**Comment by LionelColaso** [comment]
@yomato26 issue should be fixed in latest Edge Release which will be up in sometime

**Comment by yomato26** [comment]
> [@yomato26](https://github.com/yomato26) issue should be fixed in latest Edge Release which will be up in sometime

@LionelColaso thanks for the quick turn around. I downloaded most recent edge release "Edge release v1.0.22-edge2+0e2d686." and the issue is still there, its just a longer timeout. I will wait for full release :)

**Comment by LionelColaso** [comment]
> > [@yomato26](https://github.com/yomato26) issue should be fixed in latest Edge Release which will be up in sometime
> 
> [@LionelColaso](https://github.com/LionelColaso) thanks for the quick turn around. I downloaded most recent edge release "Edge release v1.0.22-edge2+0e2d686." and the issue is still there, its just a longer timeout. I will wait for full release :)

Currently, to check for internet it just checks if it can connect to google or Cloudflare server with a timeout of 30 sec can you check if you are able to ping those IP 
8.8.8.8
1.1.1.1

```
def check_internet_connection(
    primary_host: str = "8.8.8.8",
    fallback_host: str = "1.1.1.1",
    port: int = 53,
    timeout: float = 30,
```
https://github.com/RimSort/RimSort/pull/956/files

**Comment by yomato26** [comment]
Thanks @LionelColaso yeah can confirm I checked that earlier when I saw the release notes:

>ping -t 8.8.8.8

Pinging 8.8.8.8 with 32 bytes of data:
Reply from 8.8.8.8: bytes=32 time=8ms TTL=120
Reply from 8.8.8.8: bytes=32 time=7ms TTL=120
Reply from 8.8.8.8: bytes=32 time=7ms TTL=120
Reply from 8.8.8.8: bytes=32 time=29ms TTL=120
Reply from 8.8.8.8: bytes=32 time=7ms TTL=120
Reply from 8.8.8.8: bytes=32 time=7ms TTL=120
Reply from 8.8.8.8: bytes=32 time=7ms TTL=120
Reply from 8.8.8.8: bytes=32 time=8ms TTL=120
Reply from 8.8.8.8: bytes=32 time=7ms TTL=120

Ping statistics for 8.8.8.8:
    Packets: Sent = 9, Received = 9, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 7ms, Maximum = 29ms, Average = 9ms
Control-C
^C
>ping -t 1.1.1.1

Pinging 1.1.1.1 with 32 bytes of data:
Reply from 1.1.1.1: bytes=32 time=3ms TTL=60
Reply from 1.1.1.1: bytes=32 time=3ms TTL=60
Reply from 1.1.1.1: bytes=32 time=3ms TTL=60
Reply from 1.1.1.1: bytes=32 time=3ms TTL=60
Reply from 1.1.1.1: bytes=32 time=11ms TTL=60
Reply from 1.1.1.1: bytes=32 time=4ms TTL=60
Reply from 1.1.1.1: bytes=32 time=2ms TTL=60
Reply from 1.1.1.1: bytes=32 time=2ms TTL=60
Reply from 1.1.1.1: bytes=32 time=3ms TTL=60

Ping statistics for 1.1.1.1:
    Packets: Sent = 9, Received = 9, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 2ms, Maximum = 11ms, Average = 3ms

**Comment by yomato26** [comment]
Also just FYI you can't reach port 53 with a TNC given it's UDP required, don't know if this will affect your code?

**Comment by LionelColaso** [comment]
> Also just FYI you can't reach port 53 with a TNC given it's UDP required, don't know if this will affect your code?

I tested the Release just in case on Windows11 and it worked without issues for me

Are you using a firewall ?
If yes can you try to allow access to RimSort Manually in Firewall ?

**Comment by yomato26** [comment]
Can confirm allowed in Win Firewall and now it loads correctly, what has changed between .20 and .21 that Firewall is now blocking?

**Comment by LionelColaso** [comment]
> Can confirm allowed in Win Firewall and now it loads correctly, what has changed between .20 and .21 that Firewall is now blocking?

Previously, RimSort would just Run anything without checking internet is active or not
This would cause crashes and even unresponsive system if there was no internet 
to avoid such issues, This was added https://github.com/RimSort/RimSort/pull/951

**Comment by yomato26** [comment]
Ah makes sense, Thanks again for resolving so quickly!! Worth adding a note to front page to whitelist the app in firewalls I guess.

Can also confirm working in Linux once firewall rule added. Cheers :)

**Comment by LionelColaso** [comment]
> Ah makes sense, Thanks again for resolving so quickly!! Worth adding a note to front page to whitelist the app in firewalls I guess.
> 
> Can also confirm working in Linux once firewall rule added. Cheers :)

I will see if i can make it to ask user conformation to add to firewall rules or improve the notification
Thanks for your help

**Comment by yomato26** [comment]
@LionelColaso Just wanted to let you know it can also be blocked by a VPN application. I am using ProtonVPN and even with NetGuard turned off and split tunneling the VPN will block the connection. Only fully disconnecting will let it pass.

**Comment by LionelColaso** [comment]
> [@LionelColaso](https://github.com/LionelColaso) Just wanted to let you know it can also be blocked by a VPN application. I am using ProtonVPN and even with NetGuard turned off and split tunneling the VPN will block the connection. Only fully disconnecting will let it pass.

Can you redownload the latest EDGE and let me know
I just added more fallback using `HTTPS`method if `DNS` fails also updated the No Internet notification just in case
https://github.com/RimSort/RimSort/pull/959/files

**Comment by yomato26** [comment]
@LionelColaso can confirm that works! Well done team, really fast fix!
